# .github/workflows/deploy.yml
name: Build and Deploy Backend

on:
  push:
    branches:
      - Release # Corrected casing for consistency

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the application directory
            cd /var/www/sona.org.lk/backend

            # Backup the ecosystem config file before cleaning
            echo "💡 Backing up ecosystem.config.js to /tmp/..."
            cp ecosystem.config.js /tmp/ecosystem.config.js
            
            # Forcefully pull the latest source code and clean the directory
            echo "Forcefully pulling latest changes..."
            git fetch origin
            git reset --hard origin/Release
            git clean -fd

            # Restore the ecosystem config file after cleaning
            echo "✅ Restoring ecosystem.config.js from backup..."
            cp /tmp/ecosystem.config.js .

            # Create secret files
            echo "Creating secret files..."
            printf "%s" '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > sona-client-firebase-adminsdk-fbsvc-e59af42c32.json
            
            echo "Installing dependencies..."
            npm install
            
            # --- THE CRITICAL FIX: Force a clean build ---
            echo "💣 Deleting old build directory to ensure a fresh compile..."
            rm -rf dist
            
            echo "Building TypeScript project..."
            npm run build

            # --- THE FIX: Use a more reliable stop/start sequence ---
            echo "Restarting application with PM2..."
            # The '|| true' ensures the script doesn't fail if the app isn't running
            pm2 stop sona-backend || true
            pm2 start ecosystem.config.js --env production
