# .github/workflows/deploy.yml
name: Build and Deploy Backend

on:
  push:
    branches:
      - Release # Changed from 'Release' to 'release' for consistency

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the application directory
            cd /var/www/sona.org.lk/backend

            # Check if it's the first deployment
            if [ ! -d ".git" ]; then
              echo "Cloning repository for the first time..."
              git clone https://github.com/sakunasanka/Sona-backend.git .
            else
              echo "Forcefully pulling latest changes..."
              # THIS IS THE KEY FIX: Discard all local changes and pull the new version
              git fetch origin
              git reset --hard origin/release 
              git clean -fd
            fi

            echo "Creating Firebase service account file..."
            # Note: The path must match what's in your firebase.ts import
            # For '../../sona-client...json' from 'src/config/', this path is correct.
            printf "%s" '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > sona-client-firebase-adminsdk-fbsvc-e59af42c32.json
            
            echo "Installing all dependencies for build..."
            # Install ALL dependencies (including devDependencies for build)
            npm install
            
            echo "Building TypeScript project..."
            # Build the TypeScript code into JavaScript
            npm run build
            
            echo "Restarting application with PM2..."
            # Start or restart the app with PM2
            # Note: The ecosystem file should now point to the built JS file
            pm2 startOrRestart ecosystem.config.js --env production
